alias code-aws='code ~/.aws'
alias code-ssh='code ~/.ssh'
alias code-hosts='code /etc/hosts'
alias dns-resolv='cat /etc/resolv.conf'
alias first-commit='git commit --allow-empty -m "first commit"'
alias brew-save='brew leaves > $SCRIPT_DIR/homebrew/leaves.txt;brew list --cask -1 > $SCRIPT_DIR/homebrew/list-cask.txt'
alias aws-mfa-login='~/.aws/aws_mfa_login.sh'
alias backlog-daily='~/work/backlog/api.sh'
