alias awsDir='code ~/.aws'
alias sshDir='code ~/.ssh'
alias dotfilesDir='code ~/dotfiles'
alias hostsEdit='code /etc/hosts'
alias resolvCat='cat /etc/resolv.conf'
alias firstcommit='git commit --allow-empty -m "first commit"'
